apiVersion: v2
name: webapp-gin
description: A Helm Chart for Installing a WebApp inside K8s for accessing the restfulapi.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.15"

home: https://github.com/PatrickLaabs/webapp-gin
kubeVersion: '>=1.19.0-0'
maintainers:
- email: patrick.laabs@me.com
  name: patricklaabs
sources:
- https://github.com/PatrickLaabs/webapp-gin
icon: https://github.com/PatrickLaabs/patricklaabs/raw/main/images/gopher_with_coffee.gif
